FROM node:12.13.1 AS builder
MAINTAINER Tarun Baloch <tarun@workex.xyz>
# Create work directory
WORKDIR /usr/src/app

# Install runtime dependencies
RUN npm install yarn -g
# Copy app source to work directory
COPY . /usr/src/app
RUN apt-get update && apt-get -y install build-essential apt-utils
#RUN apt-get build-dep imagemagick
RUN yarn run setup
RUN yarn start build
# Install app dependencies

FROM node:12-alpine3.10

WORKDIR /usr/src/app
RUN apk add --no-cache imagemagick

ARG MAX_OLD_SPACE_SIZE=4096
ENV NODE_ENV=production
ENV GOOGLE_APPLICATION_CREDENTIALS=/usr/src/app/service_account.json
ENV ELASTIC_APM_SECRET_TOKEN=3e31e0dc-f799-473f-af20-7e4cfbd2c1f5
ENV ELASTIC_APM_SERVER_URL=https://arjun.workex.dev
ENV ELASTIC_APM_SERVICE_NAME=workex-apis-magneto
ENV ELASTIC_APM_CAPTURE_BODY=all
ENV NODE_OPTIONS="--max_old_space_size=$MAX_OLD_SPACE_SIZE"

COPY --from=builder /usr/src/app/ .

EXPOSE 3001
CMD ["node", "dist/app.js"]
