export enum Error {
    NOT_ALLOWED = 'NOT_ALLOWED',
    ALREADY_EXISTS = 'ALREADY_EXISTS',
    NOT_FOUND = 'NOT_FOUND',
    BAD_REQUEST = 'BAD_REQUEST',
    INSUFFICIENT_CONTENT = 'INSUFFICIENT_CONTENT',
    UNAUTHORIZED = 'UNAUTHORIZED',
    DELETED = 'DELETED',
    NOT_INSERTED = 'NOT_INSERTED',
}
